### ISSUE TITLE
Add buttons to the main menu!

### ISSUE THREAD

**Issue by YonatanNitzan** [YonatanNitzan/JavaCade#1]
Need to start working on the first game.

**Comment by YonatanNitzan** [comment]
Ofri, I task you to make our main menu.
The frame and panel are already there, just add a choice menu where a game can be picked and opened.

**Comment by Marxism1818** [comment]
Do I need to add it to the main frame or we'll have a few buttons on the main frame and one of them takes you to the game choice?

**Comment by YonatanNitzan** [comment]
For now just add a menu bar (text field with the arrow that opens all the options) where there only pacman.
When the game is picked it makes an intense of Pacman_Frame which opens the game.

**Comment by YonatanNitzan** [comment]
Woot woot! 
First issue done!
